apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webserver-rolebinding
subjects:
  - kind: ServiceAccount
    name: webserver-service
roleRef:
  kind: Role
  name: webserver-role
  apiGroup: rbac.authorization.k8s.io
