apiVersion: v1
kind: Service
metadata:
  name: "webserver-service"
  annotations:
    # Create endpoints also if the related pod isn't ready
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30000
    targetPort: 8000
  selector:
    app: webserver

