apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: default
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes:
      - name: kubectl
        emptyDir: {}
      initContainers:
      - name: install-kubectl
        image: allanlei/kubectl
        volumeMounts:
        - name: kubectl
          mountPath: /data
        command: ["cp", "/usr/local/bin/kubectl", "/data/kubectl"]
      containers:
      - name: webserver-app
        image: docker.io/andreatraldi/webserver:latest
        volumeMounts:
        - name: kubectl
          subPath: kubectl
          mountPath: /usr/local/bin/kubectl
      serviceAccountName: spinupcontainers
      automountServiceAccountToken: false
