apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: default
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver-app
        image: docker.io/andreatraldi/webserver:latest
      serviceAccountName: webserver-account
      automountServiceAccountToken: false
